import { Resend } from 'resend';

function fmt(amount: number) {
  return `₱${amount.toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;
}

function fmtDate(iso: string | Date) {
  return new Date(iso).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
}

export async function sendInvoiceEmail(to: string, billing: any, pdfBuffer: Buffer) {
  if (!process.env.RESEND_API_KEY) {
    throw new Error('RESEND_API_KEY not configured.');
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const invoiceNo = billing.id.slice(-8).toUpperCase();
  const from = process.env.SMTP_FROM ?? 'HRConnect <noreply@hrconnect.app>';

  await resend.emails.send({
    from,
    to,
    subject: `Invoice #${invoiceNo} — ${billing.client.name} — ${fmtDate(billing.billingDate)}`,
    html: `
      <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; color: #111;">
        <div style="background: #2563EB; padding: 24px 32px; border-radius: 8px 8px 0 0;">
          <h1 style="color: #fff; margin: 0; font-size: 22px;">HRConnect</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0;">HR & Staffing Services</p>
        </div>
        <div style="padding: 32px; border: 1px solid #E5E7EB; border-top: none; border-radius: 0 0 8px 8px;">
          <h2 style="margin: 0 0 8px; font-size: 18px;">Invoice #${invoiceNo}</h2>
          <p style="color: #6B7280; margin: 0 0 24px;">Dear ${billing.client.contactName ?? billing.client.name},</p>
          <p>Please find your invoice attached to this email.</p>
          <table style="width: 100%; border-collapse: collapse; margin: 24px 0;">
            <tr style="background: #F9FAFB;">
              <td style="padding: 12px 16px; font-weight: 600;">Client</td>
              <td style="padding: 12px 16px;">${billing.client.name}</td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: 600;">Billing Date</td>
              <td style="padding: 12px 16px;">${fmtDate(billing.billingDate)}</td>
            </tr>
            <tr style="background: #F9FAFB;">
              <td style="padding: 12px 16px; font-weight: 600;">Amount Due</td>
              <td style="padding: 12px 16px; font-size: 18px; font-weight: 700; color: #2563EB;">${fmt(billing.amount)}</td>
            </tr>
            ${billing.status === 'PAID' ? `
            <tr>
              <td style="padding: 12px 16px; font-weight: 600;">Status</td>
              <td style="padding: 12px 16px;"><span style="background: #DCFCE7; color: #16A34A; padding: 4px 12px; border-radius: 999px; font-weight: 700; font-size: 12px;">PAID</span></td>
            </tr>` : ''}
          </table>
          ${billing.paymentLinkUrl ? `
          <div style="text-align: center; margin: 32px 0;">
            <a href="${billing.paymentLinkUrl}"
               style="background: #2563EB; color: #fff; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 700; font-size: 15px;">
              Pay Online →
            </a>
          </div>` : ''}
          ${billing.notes ? `<p style="color: #6B7280; font-size: 13px; border-top: 1px solid #E5E7EB; padding-top: 16px; margin-top: 24px;">Notes: ${billing.notes}</p>` : ''}
          <p style="color: #9CA3AF; font-size: 12px; margin-top: 32px; border-top: 1px solid #E5E7EB; padding-top: 16px;">
            This invoice was generated by HRConnect. If you have questions, please reply to this email.
          </p>
        </div>
      </div>
    `,
    attachments: [
      {
        filename: `invoice-${invoiceNo}.pdf`,
        content: pdfBuffer,
      },
    ],
  });
}
